#!/bin/bash
echo domainfinderをビルドします...
go build -o domainfinder
echo synonymsをインストールします...
go install github.com/yasaichi-sandbox/synonyms
echo availableをインストールします...
go install github.com/yasaichi-sandbox/available
echo sprinkleをインストールします...
go install github.com/yasaichi-sandbox/sprinkle
echo coolifyをインストールします...
go install github.com/yasaichi-sandbox/coolify
echo domainifyをインストールします...
go install github.com/yasaichi-sandbox/domainify
echo 完了
